language: php

sudo: false
dist: xenial

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
